### PR TITLE
Revamp makefile to be more dynamic and reduce much some duplication

### PR DESCRIPTION
**Pull request by qbit**
Here is a bit of work I did semi-recently to cleanup the make situation a bit.

### CODE REVIEW

**Comment by jacobeva** [comment]
Sorry mate, I totally missed this PR. I will review soon.

**Comment by jacobeva** [comment]
Ok, it looks like this was made before #31, so I'm going to skip the changes related to ports and merge everything else :)

**Comment by jacobeva** [comment]
Thank you!

**Comment by qbit** [comment]
woo! np!

**Pull request merged**
