### PR TITLE
Updated BUILDING.md

### PR DESCRIPTION
**Pull request by nathmo**
added instruction to setup the build environnement due to pip wanting a virtual environement making things a bit more complex.

### CODE REVIEW

**Comment by jacobeva** [comment]
Thanks for the contribution! Can I ask why you think pip requires a virtual environment? I am able to use this repo without a virtual environment just fine currently.

**Comment by nathmo** [comment]
well it is my current understanding that the latest version of pip complain if you try to install a package globally and want you to either use a flag or edit a config or use a virtual environnement.

I setup the build folder on a raspberry pi and I had an error message that prevented me to install package globally using pip.

I can try to retrigger the behaviour tommorow

**Comment by jacobeva** [comment]
Ah yes I see. Not an issue. Just use pipx, or override it like I do lol. If I merge this, I won't be including the virtual environment instructions as they are unnecessary :)

**Comment by jacobeva** [comment]
Oh wait, that's the whole PR lol. My bad!

Well, I think I'll just close this tomorrow, however, your suggestion to prompt the user to install arduino-cli is wise. I will add that to `BUILDING.md`

**Comment by nathmo** [comment]
I tried to make as user friendly as possible but sometime I tend to overload the text.

Maybe just consider adding the dependency install (cmake, arduino-cli + adding it to path)
Part and leave out the venv part (or replace it with a not to overide pip if there is a error ?)

**Comment by jacobeva** [comment]
Sure, sounds good. I will do that.

**Comment by jacobeva** [comment]
I consider this closed with commits 152e7f1 and 761923e.

**Pull request closed without merging**
