### PR TITLE
ESP32: Ebyte E22 900M30S Board support

### PR DESCRIPTION
**Pull request by tomuk5**
Based off the reference Meshtastic design: 
https://github.com/NanoVHF/Meshtastic-DIY/blob/main/Schematics/E-Byte_E22/Mesh_Ebyte_E22-XXXM30S.pdf

- future pull req's to include further documentation additions to build this design and radio power output chart.

### CODE REVIEW

**Comment by jacobeva** [comment]
Very cool. Does it boot and run with your changes?

**Comment by tomuk5** [comment]
Boots and runs :) - i know i got the hardware part right as i flashed meshtastic to it and used it to prove i can send/receive and have the pins correct.

Only issue is the same one affecting ESP32 boards with the TX power mismatch preventing them from being used with Reticulum at the moment.

**Comment by jacobeva** [comment]
Excellent. Thank you for the hard work.

**Comment by tokio69** [comment]
Hello @tomuk5 , I have build this with the exact same pinout, esp32 , tranceiver,... But on the screen I get "Radio Not Found error"
In the scematic on the NanoVHF github I see that it has some flaws like where the RXEN and TXEN has to go, in the firmware it is not connected but on the scematic is is. Also GPIO26 and 33 seems to have contradictions in the scematic. I am sure it is just something small but I am already weeks trying to get a E22-900M30S working with a ESP32. Hope you can point me in the right direction on where to look further.

**Comment by tomuk5** [comment]
Hi @tokio69 
There is a deviation from the schematic in that Pin 7 (TXEN) is not connected to GPIO13 at all, its instead connected/jumpered to Pin 8 (DIO2) on the E22 itself so that it can be used as a SoftRF switch.
Pin 13 (DIO1) on the E22 connects to GPIO33 and GPIO26 is not connected.

**Pull request merged**
